export const FETCH_BOOKS_LIST_STARTED = 'FETCH_BOOKS_LIST_STARTED';
export const FETCH_BOOKS_LIST_FINISHED = 'FETCH_BOOKS_LIST_FINISHED';
export const SET_FILTERED_BOOKS = 'SET_FILTERED_BOOKS';
export const UPDATE_BOOK = 'UPDATE_BOOK';
export const ADD_BOOK = 'ADD_BOOK';
export const REMOVE_BOOK = 'REMOVE_BOOK';
